# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xD13UWPrEyWxw5sNsPI7o-Bxc90wbkCQ
"""

n=int(input())
i=1
c=0
while i<=n:
    j=1
    f=0
    if(n%i==0):
        while j<=i:
          if(i%j==0):
            f+=1
        j+=1
    if(f==2):
        c=c+1
    i=i+1
print(c)